### PR TITLE
Upgrades in Django files

### PR DESCRIPTION
**Pull request by jawaluke**
teams and installization guides are added in the project

### CODE REVIEW

**Comment by jawaharkanchana** [comment]
Need a cloud Service Provider name in a new file

**Comment by jawaluke** [comment]
File name and hoster details Required

**Comment by jawaharkanchana** [comment]
cloud : GCP
Hoster : Pivotal

**Comment by jawaluke** [comment]
open the request and its verified by ram

**Comment by jawaharkanchana** [comment]
Merged the files and also verified

**Comment by jawaluke** [comment]
Please update in future..

**Pull request merged**
